name: Release Packages
on:
    push:
        branches:
            - main

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "lts/*"

            - name: Install Dependencies
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npx turbo deploy
                  git add -A
                  git commit -m "AUTOMATED: Adds builds to server/public"
                  git push origin main
