name: Release Packages
on:
    push:
        branches:
            - main

jobs:
    release:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "lts/*"

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npx turbo deploy

            - name: Push Changes
              continue-on-error: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.email "mikecarbone@users.noreply.github.com"
                  git config --global user.name "CI"
                  git add apps/server/public
                  git commit -m "AUTOMATED: Adds builds to apps/server/public"
                  git push
